name: 🐞 Bug
description: File a bug/issue
title: "bug: "
labels: ["Bug", "Needs Triage"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: Please provide a concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Please provide a concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
        - OS:
        - Node:
        - npm:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution approach
      description: How will you solve this bug? Please provide your approach to fix this bug!
    validations:
      required: false

  - type: textarea
    attributes:
      label: Attachments
      description: |
        Links? References? Screenshots? Videos? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images/videos or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
