name: Add Labels to New Bug Reports
on:
  issues:
    types:
      - opened

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Bug Report Template
        id: check-template
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = context.payload.issue.body;

            const templateRegex = /^name: 🐞 Bug\s*description: File a bug\/issue/m;
            const isBugReport = templateRegex.test(issueBody);

            console.log(`Is Bug Report: ${isBugReport}`);
            console.log(`Issue Body: ${issueBody}`);

            if (isBugReport) {
              console.log('Bug report template detected. Adding labels...');

              const labelsToAdd = ['Bug', 'Needs Triage']; // Add your desired labels here
              const octokit = context.github;
              const issue = context.payload.issue;

              for (const label of labelsToAdd) {
                octokit.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: [label]
                });
              }

              console.log('Labels added successfully.');
            } else {
              console.log('No bug report template detected. Skipping label addition.');
            }
